CREATE TABLE `auto_adjust_advice_audit` (
`id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `audit_action` enum('UPDATE','DELETE') NOT NULL,
  `audit_timestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `auto_adjust_advice_id` bigint unsigned NOT NULL,
  `uuid` char(26) NOT NULL,
  `billing_entity_uuid` char(26) NOT NULL,
  `auto_adjust_rule_uuid` char(26) NOT NULL,
  `start_date` date NOT NULL,
  `deleted_date` date DEFAULT NULL,
  `total_periods` smallint NOT NULL,
  `evaluated_periods` smallint NOT NULL DEFAULT '0',
  `applied_periods` smallint NOT NULL DEFAULT '0',
  `max_units` decimal(12,4) DEFAULT NULL,
  `max_amount` decimal(12,3) DEFAULT NULL,
  `currency` varchar(3) DEFAULT NULL,
  `reference` varchar(50) DEFAULT NULL,
  `request_uuid` varchar(26) DEFAULT NULL,
  `created_timestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `modified_timestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `audit_id` varchar(26) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `auto_adjust_advice_audit_key1` (`uuid`,`id`)
);