CREATE TABLE `ledger_account_settlement_audit` (
`id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `audit_action` enum('UPDATE','DELETE') NOT NULL,
  `audit_timestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `ledger_account_settlement_id` bigint unsigned NOT NULL,
  `uuid` char(26) NOT NULL,
  `ledger_account_key` varchar(32) DEFAULT NULL,
  `effective_date` date DEFAULT NULL,
  `settlement_item_code` varchar(30) DEFAULT NULL,
  `settlement_desc` varchar(100) DEFAULT NULL,
  `fee_category_group` varchar(25) DEFAULT NULL,
  `revenue_group` varchar(25) DEFAULT NULL,
  `merchant_plan_uuid` char(13) DEFAULT NULL,
  `developer_uuid` varchar(13) DEFAULT NULL,
  `developer_app_uuid` varchar(13) DEFAULT NULL,
  `app_subscription_uuid` varchar(13) DEFAULT NULL,
  `app_metered_uuid` varchar(13) DEFAULT NULL,
  `created_timestamp` datetime(6) DEFAULT NULL,
  `modified_timestamp` datetime(6) DEFAULT NULL,
  `audit_id` varchar(26) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ledger_account_settlement_audit_key1` (`uuid`,`id`)
);